apiVersion: batch/v1
kind: CronJob
metadata:
  name: ping-job
  namespace: exam-xurshid
spec:
  schedule: "*/2 * * * *"  
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ping-container
            image: busybox
            command:
            - /bin/sh
            - -c
            - "ping -c 4 8.8.8.8"
          restartPolicy: OnFailure

