apiVersion: v1
kind: Pod
metadata:
  labels:
    project: practice
    author: xurshid
  name: nginx1
  namespace: exam-xurshid
spec:
  containers:
    - name: nginx1
      image: nginx:latest

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    project: practice
    author: xurshid
  name: nginx2
  namespace: exam-xurshid
spec:
  containers:
    - name: nginx2
      image: nginx:latest

