apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: repo1
  name: repo1
  namespace: exam-xurshid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repo1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: repo1
    spec:
      containers:
      - image: khurshidbek90/repo-2:v1
        name: repo1
        env:
          - name: ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: info
                key: env

          - name: LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                name: info
                key: log_leveI

          - name: GRPC_PORT
            valueFrom:
              configMapKeyRef:
                name: info
                key: grpc_port 

          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP

